INSERT INTO `APP_STATES` (ID, STATE_NAME) VALUES (1, 'CREATED');
INSERT INTO `APP_STATES` (ID, STATE_NAME) VALUES (2, 'DELETED');
INSERT INTO `APP_STATES` (ID, STATE_NAME) VALUES (3, 'VERIFIED');
INSERT INTO `APP_STATES` (ID, STATE_NAME) VALUES (4, 'REJECTED');
INSERT INTO `APP_STATES` (ID, STATE_NAME) VALUES (5, 'ACCEPTED');
INSERT INTO `APP_STATES` (ID, STATE_NAME) VALUES (6, 'PUBLISHED');




